### ISSUE TITLE
Cannot cleanup the observatorium pod/svc

### ISSUE THREAD

**Issue by clyang82** [observatorium/configuration#235]
Cannot cleanup the observatorium pod/svc/... when removing the observatorium CR. we should add the `ownerReferences` to the created pod/svc...

@nmagnezi

**Comment by brancz** [comment]
Agreed

**Comment by nmagnezi** [comment]
Thanks @clyang82, I'll look into it.

**Comment by clyang82** [comment]
@nmagnezi any progress?

**Comment by clyang82** [comment]
Thanks @brancz  @nmagnezi @rollandf
