### ISSUE TITLE
Add "Vendor" directories

### ISSUE THREAD

**Issue by rollandf** [observatorium/configuration#239]
For offline builds, there is a need for "vendor" directory.

1. Add vendor for Go libraries.
2. Support different vendor directory location for Jsonnet libraries

**Comment by rollandf** [comment]
Not needed for Go, we use Cachito.
Still needed for Jsonnet.

**Comment by kakkoyun** [comment]
This one is also getting a little bit frustrating while developing.

**Comment by rollandf** [comment]
Fixed by #257
