### ISSUE TITLE
Struct tags should not have different values than their field name

### ISSUE THREAD

**Issue by brancz** [observatorium/configuration#261]
There are a few field names that differ from their struct tag representation. This is a bad practice as it often causes confusion and is also inconsistent. They should be aligned. An example:

https://github.com/observatorium/configuration/blob/c835853933cae03341a19fef1ce8a960b54a2707/api/v1alpha1/observatorium_types.go#L26

@nmagnezi @rollandf

**Comment by rollandf** [comment]
Sure, I will fix it.

**Comment by rollandf** [comment]
This have been handled here #264 
I think it can be closed now.
