### ISSUE TITLE
Images in the CRD should be optional, with defaults handled by operator

### ISSUE THREAD

**Issue by rollandf** [observatorium/configuration#284]
We would like to have defaults for the images in the Observatorium CR. There are currently are 11 images to configure (6x Thanos,api,queryCache, memcached, memcached_exporter, receivecontroller). This could be a hurdle for the user.

1. Make images as optional in the CRD.
2. Operator will use preconfigured images if the user did not specified them in the CR.
3. The user can override one or more images.

**Comment by brancz** [comment]
I agree! If nothing else the experience that I would expect as a user is that I just have to update the version of my observatorium-operator, and my stack automatically upgrades itself due to that. Only if I have a very specific reason to do so should I need to override images.
