### ISSUE TITLE
dev up client manifest fails to spawn a working pod

### ISSUE THREAD

**Issue by nmagnezi** [observatorium/configuration#285]
the `up` manifest under `dev` fails with the following:
```
kubectl -n observatorium logs observatorium-xyz-observatorium-up-5978d796c-8p555
level=error caller=main.go:153 ts=2020-05-27T07:59:26.4076684Z name=up msg="could not parse command line flags" err="--queries-file is invalid: open /etc/up/queries.yaml: no such file or directory"
```

This is not being used in CI, is it there by mistake?
This should either be fixed or removed.

P.S.
The `up` pod created by the job does not use `--queries-file`

**Comment by brancz** [comment]
@krasi-georgiev I think you last touched this no? (cc @kakkoyun as I think you reviewed it so maybe you're familiar with it :) )

**Comment by krasi-georgiev** [comment]
checking
