### ISSUE TITLE
Setup Jaeger backend

### ISSUE THREAD

**Issue by jpkrohling** [observatorium/configuration#57]
Setup a simple Jaeger backend, made up of:

- Jaeger All in One with Badger (cc @burmanm). Once we figure out how HA can be achieved in our setup, we can split the deployments: collector in read-write mode, query in read-only mode.
- Jaeger Service, exposing the UI port (16686) and the collector's gRPC (14250).

@aditya-konarde: how can we proceed with adding the Jaeger Agent as a sidecar to the Thanos pods? Should we start with the all-in-one+service first, and the sidecar in a follow-up issue? Or is there a deployment where I could already add the sidecar as part of the initial PR?

cc @objectiser

**Comment by jpkrohling** [comment]
For those wondering: operators are a no-go in the current setup, but the idea is to move to it in the future.

**Comment by jpkrohling** [comment]
> However we still need to add the agent sidecars to Thanos

I can work on that in the coming week(s), if you can wait. Otherwise, here's the relevant commit I've shown during the presentation: https://github.com/jpkrohling/configuration/commit/c0f0faa1d855b6880365f71953a50a78c667e66c

Apart from adding a [sidecar](https://github.com/jaegertracing/jaeger-operator/blob/bad90a64177d062f7be973d73de00d404b92b95f/pkg/inject/sidecar.go#L153-L184) to the affected components, the `traceConfig` object would have to be changed, to remove the `endpoint` property, as the default client configuration will try to connect to the Agent on `localhost:6831/udp`.

**Comment by kakkoyun** [comment]
Completed by #105
